name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  # Bloc
  flutter_bloc: ^8.1.5
  google_fonts: ^6.2.1
  path: ^1.9.0
  path_provider: ^2.1.3
  sqflite: ^2.3.3
  # Components
  numberpicker: ^2.1.2
  fl_chart: ^0.67.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
